### PR TITLE
TLS

### PR DESCRIPTION
**Pull request by femto113**

### CODE REVIEW

**Comment by femto113** [comment]
Meant for this to go against my own fork, not yours, sorry for the spam.

**Comment by euangoddard** [comment]
I'm not maintaining this any more, so would be happy to make you a contributor here if you'd like to maintain this?

**Comment by femto113** [comment]
I am planning on maintaining my fork, though it's not quite ready for public consumption.  Once it is we could put a pointer to it from here.  Did you ever publish this to NPM?

**Comment by euangoddard** [comment]
I'm not sure I ever did

**Pull request closed without merging**
